##Generate random numbers that follows uniform distribution

Uniform<-function(GD, CropName, CultivarID, GenotypeFileName, ParameterProperty, ParameterAddress, TotalParameterNumber, NumberOfModelRun, RoundOfGLUE, GLUEFlag)
{

#(1)Read default values.
eval(parse(text=paste('GenotypeFilePath="',GD,'/',GenotypeFileName,'.CUL"',sep = '')));
ReadLine<-readLines(GenotypeFilePath, n=-1);
#print(ReadLine);
GenotypeFile<-as.character(ReadLine);
CultivarID<-paste('^',CultivarID, sep=""); 
LineNumber<-grep(pattern=CultivarID, GenotypeFile);
OldLine<-GenotypeFile[LineNumber];#Get the line according to the line number.

#get the ecotype file
ecotypename = substr(OldLine,31,36)
eval(parse(text=paste('EcotypeFilePath="',GD,'/',GenotypeFileName,'.ECO"',sep = '')));
readline = readLines(EcotypeFilePath)
oldline_eco = readline[stringr::str_which(readline,ecotypename)]
title_eco = readline[stringr::str_which(readline,"@ECO")]

df_eco = read.table(textConnection(oldline_eco),header = F)
header = read.table(textConnection(title_eco),header = F,comment.char = "")
header = unlist(strsplit(apply(header,FUN = as.character,MARGIN = 1 ),"\\.."))
colnames(df_eco) = header


if(CropName != "SC")
{
  Step=6;
  ValueStart<-(38-Step);
  ValueEnd<-(42-Step);
} else
{
  Step=15;
# chp changed 34 -> 37;  47 -> 51
  ValueStart<-(37-Step);
  ValueEnd<-(51-Step);
}

DefaultValue<-c();

for (i in 1:7)
{
ValueStart<-ValueStart+Step;
ValueEnd<-ValueEnd+Step;

ParameterValue<-as.numeric(substr(OldLine, ValueStart, ValueEnd));
DefaultValue<-cbind(DefaultValue, ParameterValue);
}


EcotypeValue<-df_eco[1,c("P1","P2","P3","P4","PARUE","PARU2","SLAS","HTSTD","KCAN")];
DefaultValue<-cbind(DefaultValue, EcotypeValue);


#Read the initial genotype file so as to read the default values for each parameters.

#(2) Read parameter set that have the maximum likelihood values when first round of GLUE is finished.
if ((GLUEFlag==1)&(RoundOfGLUE==2))
{
eval(parse(text = paste('PosteriorDistribution1<-read.table("',OD,
'/PosteriorDistribution_1.txt",header=TRUE,comment.char="")',sep="")));

MaximumProbability<-as.numeric(PosteriorDistribution1["MaxProbability", ]);
#print(MaximumProbability);
}

#(3) Generate random numbers
ParameterMatrix<-c();
ParameterAddress<-ParameterAddress+1;

for (i in 1:TotalParameterNumber)
{
#Generate uniform random values for P[i], i is the total number of parameters involved.
Flag<-ParameterProperty[ParameterAddress, 'Flag'];

if (GLUEFlag==1)
{
  if (RoundOfGLUE==1)
  {
    if (Flag==1)
    {
    Minimum=ParameterProperty[ParameterAddress, 'Minimum'];
    Maximum=ParameterProperty[ParameterAddress, 'Maximum'];
    } else if (Flag==0)
    {
    Minimum=DefaultValue[i];
    Maximum=DefaultValue[i];
    } else if (Flag==2)
    {
    Minimum=DefaultValue[i];
    Maximum=DefaultValue[i];
    }
  } else if (RoundOfGLUE==2)
  {
    if(Flag==2)
    {
    Minimum=ParameterProperty[ParameterAddress, 'Minimum'];
    Maximum=ParameterProperty[ParameterAddress, 'Maximum'];
    } else if (Flag==0)
    {
    Minimum=DefaultValue[i];
    Maximum=DefaultValue[i];
    } else if (Flag==1)
    {
    Minimum=MaximumProbability[i];
    Maximum=MaximumProbability[i];
    }
  }
} else if (GLUEFlag==2)
{
    if (Flag==1)
    {
    Minimum=ParameterProperty[ParameterAddress, 'Minimum'];
    Maximum=ParameterProperty[ParameterAddress, 'Maximum'];
    } else if (Flag==0)
    {
    Minimum=DefaultValue[i];
    Maximum=DefaultValue[i];
    } else if (Flag==2)
    {
    Minimum=DefaultValue[i];
    Maximum=DefaultValue[i];
    }
} else if (GLUEFlag==3)
{
     if (Flag==0)
    {
    Minimum=DefaultValue[i];
    Maximum=DefaultValue[i];
    } else if (Flag==1)
    {
    Minimum=DefaultValue[i];
    Maximum=DefaultValue[i];
    } else if (Flag==2)
    {
    Minimum=ParameterProperty[ParameterAddress, 'Minimum'];
    Maximum=ParameterProperty[ParameterAddress, 'Maximum'];
    }
}
 
GenerateParameter<-runif(NumberOfModelRun,min=as.numeric(Minimum),max=as.numeric(Maximum));
MatrixGeneratedParameter<-matrix(GenerateParameter, nrow=NumberOfModelRun, ncol=1, byrow=T);
ParameterMatrix<-cbind(ParameterMatrix, MatrixGeneratedParameter);

ParameterAddress<-ParameterAddress+1;
}

#print(ParameterMatrix);

#ParameterMatrix<-ifelse(ParameterMatrix>=999,999,ParameterMatrix);
#Set the values of some parameters such as G2 that are great than 1000 to 999, otherwise, the model will stop running.

ParameterMatrix<-ifelse(is.na(ParameterMatrix), 0, ParameterMatrix);
#If the values of some parameters are NAs which were generated by missed parameter values in the genotype file,
#they were set as zeros.

#print(ParameterMatrix);

return(ParameterMatrix);                   
}

